In [1]:
#importo librerias a ocupar
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
#Realizo lectura de archivo parquet
df17 = pd.read_parquet(path='C:\\empresa\\analisis 02\\actualizadosv3\\df17.parquet')
df17.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,Deuda_DMora,Deuda_DVencida,Deuda_DCastigo,Mora_R04_Hoy,FALLECIDO,BASE_NEGRO,Marca_Inhibido
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,0.0,0.0,0.0,No,0,0,0
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,26000.0,10000.0,0.0,Si,0,0,0

In [3]:
#Realizo lectura de archivo excel
df18 = pd.read_excel('C:\\empresa\\analisis 02\\actualizadosv3\\Marca_Carven.xlsx')
df18.head(10)

        RUT Periodo_Min  Marca_Castigo  Marca_Pagado_2años
0   7312794  2020-07-01              1                 1.0
1   9339768         NaT              0                 NaN
2   9769068         NaT              0                 NaN
3  11206097  2020-07-01              1                 1.0
4  11473230         NaT              1                 NaN
5  12043190         NaT              0                 NaN
6  16230322         NaT              0                 NaN
7  16289201         NaT              0                 NaN
8  16424275         NaT              1                 NaN
9  16482699         NaT              0                 NaN

In [4]:
#Reemplazo los valores NaN por 0 en la columna Marca_Pagado_2años, luego cambio el tipo de dato a int
df18['Marca_Pagado_2años'] = df18['Marca_Pagado_2años'].fillna(0)
df18['Marca_Pagado_2años'] = df18['Marca_Pagado_2años'].astype(int)
df18.head(10)

        RUT Periodo_Min  Marca_Castigo  Marca_Pagado_2años
0   7312794  2020-07-01              1                   1
1   9339768         NaT              0                   0
2   9769068         NaT              0                   0
3  11206097  2020-07-01              1                   1
4  11473230         NaT              1                   0
5  12043190         NaT              0                   0
6  16230322         NaT              0                   0
7  16289201         NaT              0                   0
8  16424275         NaT              1                   0
9  16482699         NaT              0                   0

In [5]:
#Hago un merge de los df17 y df18 para que me agreguen mas informacion a los ruts coincidentes, en este caso las columnas 
df19 = pd.merge(df17, df18, on='RUT', how='left')
df19.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,Deuda_DMora,Deuda_DVencida,Deuda_DCastigo,Mora_R04_Hoy,FALLECIDO,BASE_NEGRO,Marca_Inhibido,Periodo_Min,Marca_Castigo,Marca_Pagado_2años
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,NaT,0,0
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,0.0,0.0,0.0,No,0,0,0,NaT,1,0
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,NaT,0,0
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,NaT,0,0
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,NaT,0,0
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,NaT,0,0
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,NaT,0,0
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,NaT,0,0
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,0.0,0.0,0.0,No,0,0,0,2020-07-01,1,1
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,26000.0,10000.0,0.0,Si,0,0,0,NaT,0,0

In [6]:
#lectura de archivo SPSS y de columnas especificas y luego cambio de nombre de columna CTARUT a RUT
df20 = pd.read_spss(path='C:\\empresa\\analisis 02\\actualizadosv3\\insolvencia.sav')
df20 = df20.rename(columns={'CTARUT':'RUT'})
df20.head(10)

          RUT  INSOLVENCIA
0  76308584.0          1.0
1   8550702.0          1.0
2  12017488.0          1.0
3  76423042.0          1.0
4  16114893.0          1.0
5   6568326.0          1.0
6  15624706.0          1.0
7   5823719.0          1.0
8  17108964.0          1.0
9  15525450.0          1.0

In [7]:
#Hago un merge de los df19 y df20 para que me agreguen mas informacion a los ruts coincidentes, en este caso las columnas
df21 = pd.merge(df19, df20, on='RUT', how='left')
df21.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Deuda_DVencida,Deuda_DCastigo,Mora_R04_Hoy,FALLECIDO,BASE_NEGRO,Marca_Inhibido,Periodo_Min,Marca_Castigo,Marca_Pagado_2años,INSOLVENCIA
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,NaN
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0.0,0.0,No,0,0,0,NaT,1,0,NaN
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,NaN
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,NaN
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,NaN
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,NaN
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,NaN
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,NaN
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,2020-07-01,1,1,NaN
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,10000.0,0.0,Si,0,0,0,NaT,0,0,NaN

In [8]:
#Reemplazo los valores NaN por 0 en la columna INSOLVENCIA luego cambio el tipo de dato a int
df21['INSOLVENCIA'] = df21['INSOLVENCIA'].fillna(0)
df21['INSOLVENCIA'] = df21['INSOLVENCIA'].astype(int)
df21.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Deuda_DVencida,Deuda_DCastigo,Mora_R04_Hoy,FALLECIDO,BASE_NEGRO,Marca_Inhibido,Periodo_Min,Marca_Castigo,Marca_Pagado_2años,INSOLVENCIA
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,0
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0.0,0.0,No,0,0,0,NaT,1,0,0
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,0
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,0
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,0
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,0
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,0
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,NaT,0,0,0
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,0.0,0.0,No,0,0,0,2020-07-01,1,1,0
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,10000.0,0.0,Si,0,0,0,NaT,0,0,0

In [9]:
#lectura de archivo SPSS y de columnas especificas y luego cambio de nombre de columna CTARUT a RUT y comvierto el tipo de dato a int
df22 = pd.read_spss(path='C:\\empresa\\analisis 02\\actualizadosv3\\GSE_FAM_2022_02.sav', usecols=['CTARUT', 'NVO_GSE', 'GSE_FAM'])
df22 = df22.rename(columns={'CTARUT':'RUT'})
df22['RUT'] = df22['RUT'].astype(int)
df22.head(10)

   RUT NVO_GSE GSE_FAM
0    1       E       E
1    2      C3      C3
2    3       E       E
3    4       D       D
4    5       E       E
5    6       D       D
6    7      C3      C3
7    8       D       D
8    9       D       D
9   10      C3      C3

In [10]:
#Hago un merge de los df21 y df22 para que me agreguen mas informacion a los ruts coincidentes, en este caso las columnas
df23 = pd.merge(df21, df22, on='RUT', how='left')
df23.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Mora_R04_Hoy,FALLECIDO,BASE_NEGRO,Marca_Inhibido,Periodo_Min,Marca_Castigo,Marca_Pagado_2años,INSOLVENCIA,NVO_GSE,GSE_FAM
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,No,0,0,0,NaT,0,0,0,C2,C2
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,No,0,0,0,NaT,1,0,0,E,E
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,No,0,0,0,NaT,0,0,0,C1a,C1a
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,No,0,0,0,NaT,0,0,0,C1a,C1a
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,No,0,0,0,NaT,0,0,0,C1a,C1a
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,No,0,0,0,NaT,0,0,0,AB,AB
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,No,0,0,0,NaT,0,0,0,C1a,C1a
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,No,0,0,0,NaT,0,0,0,C2,C2
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,No,0,0,0,2020-07-01,1,1,0,C1a,C1a
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,Si,0,0,0,NaT,0,0,0,AB,AB

In [11]:
#lectura de archivo SPSS y de columnas especificas y luego cambio de nombre de columna CTARUT a RUT, MORA_EQ_sum_12_Meses a Mora_EQ_12_Meses y comvierto el tipo de datos a int
df24 = pd.read_spss(path='C:\\empresa\\analisis 02\\actualizadosv3\\mora_equifax_12_meses.sav')
df24 = df24.rename(columns={'CTARUT':'RUT', 'MORA_EQ_sum_12_Meses':'Mora_EQ_12_Meses'})
df24[['RUT', 'Mora_EQ_12_Meses']] = df24[['RUT', 'Mora_EQ_12_Meses']].astype(int)
df24.head(10)

        RUT  Mora_EQ_12_Meses
0  15329396           3136664
1   7739392           1262548
2  12518061             36781
3  15490373              9890
4  12765413            241766
5  15971343          18160423
6  13883216           4538784
7  11514760          18578040
8  24413972           1006860
9  16032513           1046631

In [12]:
#Hago un merge de los df23 y df24 para que me agreguen mas informacion a los ruts coincidentes, en este caso las columnas
#Luego reemplazo los valores NaN por 0 en la columna Mora_EQ_12_Meses y cambio el tipo de dato a int
df25 = pd.merge(df23, df24, on='RUT', how='left')
df25['Mora_EQ_12_Meses'] = df25['Mora_EQ_12_Meses'].fillna(0)
df25['Mora_EQ_12_Meses'] = df25['Mora_EQ_12_Meses'].astype(int)
df25.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,FALLECIDO,BASE_NEGRO,Marca_Inhibido,Periodo_Min,Marca_Castigo,Marca_Pagado_2años,INSOLVENCIA,NVO_GSE,GSE_FAM,Mora_EQ_12_Meses
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,NaT,0,0,0,C2,C2,0
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0,0,0,NaT,1,0,0,E,E,0
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,0,NaT,0,0,0,C1a,C1a,0
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,0,0,0,NaT,0,0,0,C1a,C1a,12826
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,NaT,0,0,0,C1a,C1a,0
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,NaT,0,0,0,AB,AB,0
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,NaT,0,0,0,C1a,C1a,0
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,0,NaT,0,0,0,C2,C2,0
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,0,0,0,2020-07-01,1,1,0,C1a,C1a,11518
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,0,0,0,NaT,0,0,0,AB,AB,0

In [13]:
# lectura de archivo SPSS y de columnas especificas y luego cambio de nombre de columna 
# CTARUT a RUT, Deuda_DMora_SUM a Deuda_DMora_12M, Deuda_DVencida_SUM a Deuda_DVencida_12M, Deuda_DCastigo_SUM a Deuda_DCastigo_12M
df26 = pd.read_spss(path='C:\\empresa\\analisis 02\\actualizadosv3\\mora_r04_12_meses.sav')
df26 = df26.rename(columns={'CTARUT':'RUT', 'Deuda_DMora_SUM':'Deuda_DMora_12M', 'Deuda_DVencida_SUM':'Deuda_DVencida_12M', 'Deuda_DCastigo_SUM':'Deuda_DCastigo_12M'})
df26.head(10)

          RUT  Deuda_DMora_12M  Deuda_DVencida_12M  Deuda_DCastigo_12M
0  10542907.0              0.0                 0.0                 0.0
1  11843136.0              0.0                 0.0                 0.0
2  16908918.0              0.0                 0.0                 0.0
3   5499770.0              0.0                 0.0                 0.0
4  25984406.0          27000.0                 0.0                 0.0
5  76852911.0              0.0                 0.0                 0.0
6   6533201.0              0.0                 0.0                 0.0
7  16781430.0              0.0                 0.0            119000.0
8   8264624.0              0.0                 0.0                 0.0
9  14582228.0              0.0                 0.0                 0.0

In [19]:
#Hago un merge de los df25 y df26 para que me agreguen mas informacion a los ruts coincidentes, en este caso las columnas.
#Luego reemplazo los valores NaN por 0 en varias columnas y cambio el tipo de dato a int
df27 = pd.merge(df25, df26, on='RUT', how='left')
df27[['Deuda_DMora_12M', 'Deuda_DVencida_12M', 'Deuda_DCastigo_12M']] = df27[['Deuda_DMora_12M', 'Deuda_DVencida_12M', 'Deuda_DCastigo_12M']].fillna(0)
df27[['Deuda_DMora_12M', 'Deuda_DVencida_12M', 'Deuda_DCastigo_12M']] = df27[['Deuda_DMora_12M', 'Deuda_DVencida_12M', 'Deuda_DCastigo_12M']].astype(int)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Periodo_Min,Marca_Castigo,Marca_Pagado_2años,INSOLVENCIA,NVO_GSE,GSE_FAM,Mora_EQ_12_Meses,Deuda_DMora_12M,Deuda_DVencida_12M,Deuda_DCastigo_12M
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,NaT,0,0,0,C2,C2,0,0,0,0
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,NaT,1,0,0,E,E,0,0,0,0
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,NaT,0,0,0,C1a,C1a,0,0,0,0
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,NaT,0,0,0,C1a,C1a,12826,5000,0,0
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,NaT,0,0,0,C1a,C1a,0,0,0,0
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,NaT,0,0,0,AB,AB,0,0,0,0
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,NaT,0,0,0,C1a,C1a,0,0,0,0
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,NaT,0,0,0,C2,C2,0,0,0,0
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,2020-07-01,1,1,0,C1a,C1a,11518,0,0,0
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,NaT,0,0,0,AB,AB,0,48000,24000,0

In [20]:
df27['fecha_analisis'] = dt.datetime(2022,7,1)
df27['Dif_Fechas'] = round(((df27.fecha_analisis - df27.Periodo_Min) / np.timedelta64(1, 'M')).fillna(0))
df27['Dif_Fechas'] = df27['Dif_Fechas'].astype(int)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Marca_Pagado_2años,INSOLVENCIA,NVO_GSE,GSE_FAM,Mora_EQ_12_Meses,Deuda_DMora_12M,Deuda_DVencida_12M,Deuda_DCastigo_12M,fecha_analisis,Dif_Fechas
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,C2,C2,0,0,0,0,2022-07-01,0
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0,0,E,E,0,0,0,0,2022-07-01,0
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,C1a,C1a,0,0,0,0,2022-07-01,0
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,0,0,C1a,C1a,12826,5000,0,0,2022-07-01,0
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,C1a,C1a,0,0,0,0,2022-07-01,0
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,AB,AB,0,0,0,0,2022-07-01,0
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,C1a,C1a,0,0,0,0,2022-07-01,0
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,C2,C2,0,0,0,0,2022-07-01,0
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,1,0,C1a,C1a,11518,0,0,0,2022-07-01,24
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,0,0,AB,AB,0,48000,24000,0,2022-07-01,0

In [23]:
#tramifico la columna Dif_Fechas en tramos de castigos por meses, luego la aplico a todo el df27 retornando los resultado en la columna Tramos_Castigos
def tramos_castigos(fechas):
    if fechas['Dif_Fechas'] > 0 and fechas['Dif_Fechas'] <= 6:
        return '<= 6 meses'
    elif fechas['Dif_Fechas'] > 6 and fechas['Dif_Fechas'] <= 12:
        return 'Entre 6 a 12 Meses'
    elif fechas['Dif_Fechas'] > 12 and fechas['Dif_Fechas'] <= 24:
        return 'Entre 1 a 2 Años'
    elif fechas['Dif_Fechas'] > 24:
        return 'Mayor a 2 Años'
    else:
        return 'No Castigado'

df27['Tramos_Castigos'] = df27.apply(tramos_castigos, axis=1)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,INSOLVENCIA,NVO_GSE,GSE_FAM,Mora_EQ_12_Meses,Deuda_DMora_12M,Deuda_DVencida_12M,Deuda_DCastigo_12M,fecha_analisis,Dif_Fechas,Tramos_Castigos
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,C2,C2,0,0,0,0,2022-07-01,0,No Castigado
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0,E,E,0,0,0,0,2022-07-01,0,No Castigado
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,C1a,C1a,0,0,0,0,2022-07-01,0,No Castigado
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,0,C1a,C1a,12826,5000,0,0,2022-07-01,0,No Castigado
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,C1a,C1a,0,0,0,0,2022-07-01,0,No Castigado
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,AB,AB,0,0,0,0,2022-07-01,0,No Castigado
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,C1a,C1a,0,0,0,0,2022-07-01,0,No Castigado
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,C2,C2,0,0,0,0,2022-07-01,0,No Castigado
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,0,C1a,C1a,11518,0,0,0,2022-07-01,24,Entre 1 a 2 Años
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,0,AB,AB,0,48000,24000,0,2022-07-01,0,No Castigado

In [30]:
#Creo una columna que me indique si el cliente tiene una mora hoy o no en Equifax o en R04, luego la aplico a todo el df27 retornando los resultado en la columna Mora_Hoy
def mora_hoy_saber(mora_hoy_o_no):
    if mora_hoy_o_no['Mora_EQFX_Hoy'] == "Si" or mora_hoy_o_no['Mora_R04_Hoy'] == "Si":
        return 'Si'
    else:
        return 'No'
    
df27['Mora_Hoy'] = df27.apply(mora_hoy_saber, axis=1)
df27.head(10)

Mora_Hoy
No    918
Si    436
Name: count, dtype: int64

In [25]:
#Reviso si existen moras antiguas en los ultimos 12 meses en R04, si es asi retorno un Si, sino un No
def mora_antigua(numero_moras):
    if numero_moras['Deuda_DMora_12M'] > 0 or numero_moras['Deuda_DVencida_12M'] > 0 or numero_moras['Deuda_DCastigo_12M'] > 0:
        return 'Si'
    else:
        return 'No'
    
df27['Mora_Antigua_R04'] = df27.apply(mora_antigua, axis=1)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,NVO_GSE,GSE_FAM,Mora_EQ_12_Meses,Deuda_DMora_12M,Deuda_DVencida_12M,Deuda_DCastigo_12M,fecha_analisis,Dif_Fechas,Tramos_Castigos,Mora_Antigua_R04
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,C2,C2,0,0,0,0,2022-07-01,0,No Castigado,No
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,E,E,0,0,0,0,2022-07-01,0,No Castigado,No
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,C1a,C1a,0,0,0,0,2022-07-01,0,No Castigado,No
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,C1a,C1a,12826,5000,0,0,2022-07-01,0,No Castigado,Si
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,C1a,C1a,0,0,0,0,2022-07-01,0,No Castigado,No
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,AB,AB,0,0,0,0,2022-07-01,0,No Castigado,No
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,C1a,C1a,0,0,0,0,2022-07-01,0,No Castigado,No
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,C2,C2,0,0,0,0,2022-07-01,0,No Castigado,No
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,C1a,C1a,11518,0,0,0,2022-07-01,24,Entre 1 a 2 Años,No
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,AB,AB,0,48000,24000,0,2022-07-01,0,No Castigado,Si

In [27]:
#Reviso si existen moras antiguas en los ultimos 12 meses en Equifax, si es asi retorno un Si, sino un No. Luego aplico la funcion a todo el df27, generado la columna Mora_Antigua_EQFX donde se almacenan los resultados.
def mora_antigua_eqfx(numero_moras_eqfx):
    if numero_moras_eqfx['Mora_EQ_12_Meses'] > 0:
        return 'Si'
    else:
        return 'No'

df27['Mora_Antigua_EQFX'] = df27.apply(mora_antigua_eqfx, axis=1)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,GSE_FAM,Mora_EQ_12_Meses,Deuda_DMora_12M,Deuda_DVencida_12M,Deuda_DCastigo_12M,fecha_analisis,Dif_Fechas,Tramos_Castigos,Mora_Antigua_R04,Mora_Antigua_EQFX
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,C2,0,0,0,0,2022-07-01,0,No Castigado,No,No
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,E,0,0,0,0,2022-07-01,0,No Castigado,No,No
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,C1a,0,0,0,0,2022-07-01,0,No Castigado,No,No
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,C1a,12826,5000,0,0,2022-07-01,0,No Castigado,Si,Si
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,C1a,0,0,0,0,2022-07-01,0,No Castigado,No,No
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,AB,0,0,0,0,2022-07-01,0,No Castigado,No,No
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,C1a,0,0,0,0,2022-07-01,0,No Castigado,No,No
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,C2,0,0,0,0,2022-07-01,0,No Castigado,No,No
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,C1a,11518,0,0,0,2022-07-01,24,Entre 1 a 2 Años,No,Si
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,AB,0,48000,24000,0,2022-07-01,0,No Castigado,Si,No

In [29]:
#Reviso si existen moras antiguas en los ultimos 12 meses en R04 y Equifax, si es asi retorno un Si, sino un No. Luego aplico la funcion a todo el df27, generado la columna Mora_antigua_ambas donde se almacenan los resultados.
def mora_antigua_ambas(numero_moras_ambas):
    if numero_moras_ambas['Mora_Antigua_R04'] == 'Si' or numero_moras_ambas['Mora_Antigua_EQFX'] == 'Si':
        return 'Si'
    else:
        return 'No'
    
df27['Mora_antigua_ambas'] = df27.apply(mora_antigua_ambas, axis=1)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Mora_EQ_12_Meses,Deuda_DMora_12M,Deuda_DVencida_12M,Deuda_DCastigo_12M,fecha_analisis,Dif_Fechas,Tramos_Castigos,Mora_Antigua_R04,Mora_Antigua_EQFX,Mora_antigua_ambas
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,0,2022-07-01,0,No Castigado,No,No,No
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0,0,0,0,2022-07-01,0,No Castigado,No,No,No
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,0,0,2022-07-01,0,No Castigado,No,No,No
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,12826,5000,0,0,2022-07-01,0,No Castigado,Si,Si,Si
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,0,2022-07-01,0,No Castigado,No,No,No
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,0,2022-07-01,0,No Castigado,No,No,No
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,0,0,2022-07-01,0,No Castigado,No,No,No
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,0,0,2022-07-01,0,No Castigado,No,No,No
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,11518,0,0,0,2022-07-01,24,Entre 1 a 2 Años,No,Si,Si
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,0,48000,24000,0,2022-07-01,0,No Castigado,Si,No,Si

In [32]:
#Reviso si el cliente tiene mora hoy o bien antigua, si es en ambas, en una si y en otra no, o en ninguna. En base a eso, genero una nueva columna llamada Tiene_Mora donde se almacenan los resultados.
def tiene_mora_o_no(tener_mora):
    if tener_mora['Mora_Hoy'] == 'Si' and tener_mora['Mora_antigua_ambas'] == 'Si':
        return 'Ambas'
    elif tener_mora['Mora_Hoy'] == 'Si' and tener_mora['Mora_antigua_ambas'] == 'No':
        return 'Mora Nueva'
    elif tener_mora['Mora_Hoy'] == 'No' and tener_mora['Mora_antigua_ambas'] == 'Si':
        return 'Mora Antigua'
    else:
        return 'Sin Mora'

df27['Tiene_Mora'] = df27.apply(tiene_mora_o_no, axis=1)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Deuda_DVencida_12M,Deuda_DCastigo_12M,fecha_analisis,Dif_Fechas,Tramos_Castigos,Mora_Antigua_R04,Mora_Antigua_EQFX,Mora_antigua_ambas,Mora_Hoy,Tiene_Mora
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0,0,2022-07-01,0,No Castigado,No,No,No,Si,Mora Nueva
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,0,No Castigado,Si,Si,Si,No,Mora Antigua
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,0,0,2022-07-01,24,Entre 1 a 2 Años,No,Si,Si,No,Mora Antigua
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,24000,0,2022-07-01,0,No Castigado,Si,No,Si,Si,Ambas

In [37]:
#Reviso la maxima mora que hay entre las columnas de MTO_TOT_BIC y MTO_TOT_MCC_EQFX, y retorno el valor maximo entre las 2. Luego aplico la funcion a todo el df27, generado la columna Mora_Max donde se almacenan los resultados.
def mora_maxima(mora_max_):
    return mora_max_[['MTO_TOT_BIC','MTO_TOT_MCC_EQFX']].max(axis=0)

df27['Mora_Max'] = df27.apply(mora_maxima, axis=1)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,Deuda_DCastigo_12M,fecha_analisis,Dif_Fechas,Tramos_Castigos,Mora_Antigua_R04,Mora_Antigua_EQFX,Mora_antigua_ambas,Mora_Hoy,Tiene_Mora,Mora_Max
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,0,2022-07-01,0,No Castigado,No,No,No,Si,Mora Nueva,372968.0
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,0,No Castigado,Si,Si,Si,No,Mora Antigua,0.0
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,0,2022-07-01,24,Entre 1 a 2 Años,No,Si,Si,No,Mora Antigua,0.0
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,0,2022-07-01,0,No Castigado,Si,No,Si,Si,Ambas,0.0

In [42]:
#tramifico la mora maxima, para poder hacer un analisis mas facil de la misma. Luego aplico la funcion a todo el df27, generado la columna Tramos_Mora_Max donde se almacenan los resultados.
def tramos_mora_max(tramos_moras_max):
    if tramos_moras_max['Mora_Max'] > 0 and tramos_moras_max['Mora_Max'] <= 10000:
        return '<= 10m'
    elif tramos_moras_max['Mora_Max'] > 10000 and tramos_moras_max['Mora_Max'] <= 30000:
        return 'Entre 10-30m'
    elif tramos_moras_max['Mora_Max'] > 30000 and tramos_moras_max['Mora_Max'] <= 50000:
        return 'Entre 30-50m'
    elif tramos_moras_max['Mora_Max'] > 50000 and tramos_moras_max['Mora_Max'] <= 100000:
        return 'Entre 50-100m'
    elif tramos_moras_max['Mora_Max'] > 100000:
        return '> 100m'
    else:
        return 'Sin Mora'
    
df27['Mora_Max_Tramos'] = df27.apply(tramos_mora_max, axis=1)
df27.head(10)

,RUT,Cliente,CUPO,Tipo_Oferta,RAZON,MTO_TOT_BIC,MTO_TOT_MCC,MTO_TOT_BIC_EQFX,MTO_TOT_MCC_EQFX,Mora_EQFX_Hoy,...,fecha_analisis,Dif_Fechas,Tramos_Castigos,Mora_Antigua_R04,Mora_Antigua_EQFX,Mora_antigua_ambas,Mora_Hoy,Tiene_Mora,Mora_Max,Mora_Max_Tramos
0,5817580,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0,Sin Mora
1,6583523,0,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,372968.0,Si,...,2022-07-01,0,No Castigado,No,No,No,Si,Mora Nueva,372968.0,> 100m
2,6825583,0,1860000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0,Sin Mora
3,6904020,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,0.0,0.0,0.0,No,...,2022-07-01,0,No Castigado,Si,Si,Si,No,Mora Antigua,0.0,Sin Mora
4,7035722,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0,Sin Mora
5,7208753,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0,Sin Mora
6,7230743,1,0,Sin Oferta NC,Ya es cliente,0.0,0.0,0.0,0.0,No,...,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0,Sin Mora
7,7308382,0,480000,Otro,NaN,0.0,0.0,0.0,0.0,No,...,2022-07-01,0,No Castigado,No,No,No,No,Sin Mora,0.0,Sin Mora
8,7312794,1,0,Sin Oferta NC,No entra Minimo Politica,0.0,0.0,0.0,0.0,No,...,2022-07-01,24,Entre 1 a 2 Años,No,Si,Si,No,Mora Antigua,0.0,Sin Mora
9,7746121,1,0,Sin Oferta NC,MORA R04 o Equifax,0.0,35899.0,0.0,0.0,Si,...,2022-07-01,0,No Castigado,Si,No,Si,Si,Ambas,0.0,Sin Mora

In [43]:
#Escritura del archivo final
df27.to_excel('C:\\empresa\\analisis 02\\actualizadosv3\\resultadopython.xlsx', sheet_name='ResultadOrion', index=False)